[package]
name = "Barclay_OS"
version = "0.2.0"
edition = "2021"

[dependencies]


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "barclay_kernel"
path = "src/main.rs"
test = false
doctest = false
bench = false
