[target.riscv64gc-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tsrc/kernel.ld"]

[build]
target = "riscv64gc-unknown-none-elf"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "alloc", "compiler_builtins"]
